name: CI

on:
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Install vulkan SDK
    - run: |
        curl https://vulkan.lunarg.com/sdk/home#sdk/downloadConfirm/1.1.130.0/windows/VulkanSDK-1.1.130.0-Installer.exe -o vulkan-installer.exe
        vulkan-installer.exe
