name: CI

on:
  pull_request:
    branches: 
      - master

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Run cmake
      run: |
        mkdir build
        cd build
        cmake ../
